version: "3.8"

services:
  trino:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trino
    ports:
      - "8088:8088"
    volumes:
      - ./config:/etc/trino
    restart: always  
    networks:
      - my-shared-network


networks:
  my-shared-network:
    external: true